name: Setup Harness Delegate

on:
  push:
    branches:
      - harness-test-QA
      - harness-test-PROD
  workflow_dispatch:  

jobs:
  setup-harness-delegate:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Harness Delegate (Docker)
        run: |
          docker run --cpus=1 --memory=2g \
            -e DELEGATE_NAME=docker-delegate \
            -e NEXT_GEN="true" \
            -e DELEGATE_TYPE="DOCKER" \
            -e ACCOUNT_ID=o2VrMRDORdytEE8OS6sOUw \
            -e DELEGATE_TOKEN=NDdiZmM5YmFlN2NhYzdmNmRmNjNkODU0YjBlOTBmYTQ= \
            -e DELEGATE_TAGS="" \
            -e MANAGER_HOST_AND_PORT=https://app.harness.io \
            harness/delegate:25.03.85403

      - name: Verify Delegate Registration
        run: |
          sleep 30 
          curl -X GET "https://app.harness.io/gateway/api/v1/delegates?accountIdentifier=o2VrMRDORdytEE8OS6sOUw"
